Docs for iZone component.
home-assistant/home-assistant.io pull request #9635
Opened 2019-06-15 12:46 UTC by Swamp-Ig

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

2019-06-15 13:56 UTC, klaasnicolaas requested changes

2019-06-15 13:56 UTC, klaasnicolaas commented on source/_components/pizone.markdown
> +izone:
I mis configuration variables explanation 😉 https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration

2019-06-21 23:13 UTC, Zac300 commented on source/_components/pizone.markdown
> +The Daikin component can be configured in two ways.
Should this say iZone instead of Daikin?

2019-06-22 04:15 UTC, Swamp-Ig commented
Changes made as requested

2019-06-22 08:42 UTC, klaasnicolaas requested changes

2019-06-22 08:42 UTC, klaasnicolaas commented on source/_components/pizone.markdown
> +ha_release: 0.95
```suggestion
ha_release: 0.96
```

2019-09-19 21:35 UTC, MartinHjelmare commented on source/_components/pizone.markdown
> +ha_release: 0.96
"0.100"

2019-09-19 23:48 UTC, MartinHjelmare submitted a review, later dismissed

2019-09-20 10:28 UTC, klaasnicolaas submitted a review, later dismissed

2019-09-21 20:24 UTC, frenck approved these changes
Thanks, @Swamp-Ig! 👍

2019-09-21 20:24 UTC, merged